proj4/app4/urls.py
from os import name
from django.urls import path

from app4 import views

app_name = 'app4'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('relative/',views.relative,name='relative')

]

proj4/proj4/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from app4 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('app4/',include('app4.urls'))
]

proj4/app4/models.py
from django.db import models

# Create your models here.

proj4/app4/views.py
from os import name
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request): 
    context_dict = {'text':'hello world hellos prameet','number':100}
    return render(request,'app4/index.html',context=context_dict)

def other(request):
    return render(request,'app4/other.html')

def relative(request):
    return render(request,'app4/relative_url_templates.html')

proj4/templates/app4/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">HOME</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'app4:other' %}">Other</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}

        {% endblock %}

    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>

</html>

proj4/templates/app4/index.html
<!DOCTYPE html>
{% extends "app4/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO INDEX</h1>
        <h3>This is index.html example</h3>
        <h1>{{number | add:'10'}}</h1>
        <h1>{{text | cut:'hello'}}</h1>
        <h1>{{text | upper}}</h1>

    {% endblock %}

proj4/templates/app4/other.html
<!DOCTYPE html>
{% extends "app4/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO OTHER</h1>
        <h3>Example of template inheritance </h3>
    {% endblock %}

proj4/templates/app4/relative_url_templates.html
<!DOCTYPE html>
{% extends "app4/base.html" %}
    {% block body_block %}
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'app4:other' %}">The other page</a>
    <a href="{% url 'admin:index'%}">ADMIN</a>
    {% endblock %}
</body>
</html>